import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  appContainer: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  deleteButton: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#c1272d',
    marginRight: 'auto',
  },
  deleteButtonText: {
    color: '#c1272d',
    fontWeight: 'bold',
    fontSize: 16,
  },
  topNav: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 18,
    paddingHorizontal: 24,
    backgroundColor: '#f5f5f5',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  navTitle: {
    fontWeight: 'bold',
    fontSize: 24,
    color: 'black',
  },
  navRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  profileIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#e0e0ff',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  logoutButton: {
    backgroundColor: '#333',
    borderRadius: 5,
    paddingVertical: 8,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  logoutText: {
    color: '#fff',
    fontWeight: '500',
  },
  mainContent: {
    flex: 1,
    backgroundColor: '#bb3737',
  },
  actionBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 24,
    backgroundColor: '#bb3737',
    justifyContent: 'space-between',
  },
  searchContainer: {
    flex: 1,
    marginRight: 16,
  },
  searchInput: {
    backgroundColor: '#fff',
    borderRadius: 25,
    paddingVertical: 12,
    paddingHorizontal: 20,
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    width: '100%',
    color: '#333',
  },
  addButton: {
    backgroundColor: '#333',
    borderRadius: 5,
    paddingVertical: 10,
    paddingHorizontal: 18,
    alignItems: 'center',
  },
  addButtonText: {
    color: '#fff',
    fontWeight: '500',
    fontSize: 15,
  },
  contentArea: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 5,
    marginHorizontal: 16,
    marginBottom: 16,
    padding: 10,
    minHeight: 300,
    elevation: 2,
  },
  companyRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    paddingVertical: 14,
    paddingHorizontal: 4,
  },
  legalName: {
    fontSize: 17,
    color: 'black',
    fontWeight: '500',
  },
  brandName: {
    color: '#555',
    fontSize: 13,
  },
  projects: {
    color: '#888',
    fontSize: 12,
  },
  rowActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  actionIcon: {
    marginLeft: 8,
    padding: 6,
  },
  actionIconText: {
    fontSize: 20,
    color: '#c1272d',
  },
  noResults: {
    textAlign: 'center',
    color: '#888',
    fontSize: 16,
    marginVertical: 24,
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: 8,
    width: '85%',
    maxWidth: 400,
    elevation: 5,
    paddingBottom: 10,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 18,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#c1272d',
  },
  closeButton: {
    fontSize: 28,
    color: '#aaa',
    fontWeight: 'bold',
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  modalBody: {
    padding: 18,
  },
  modalFooter: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
    padding: 18,
    borderTopWidth: 1,
    borderTopColor: '#eee',
  },
  formGroup: {
    marginBottom: 14,
  },
  formGroupRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  formLabel: {
    marginBottom: 6,
    fontWeight: '500',
    color: '#333',
    fontSize: 15,
    marginRight: 10,
  },
  formInput: {
    width: '100%',
    padding: 10,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 4,
    fontSize: 16,
    color: '#333',
    backgroundColor: '#fafafa',
  },
  button: {
    backgroundColor: '#c1272d',
    borderRadius: 4,
    paddingVertical: 10,
    paddingHorizontal: 22,
    alignItems: 'center',
    marginLeft: 8,
  },
  buttonText: {
    color: '#fff',
    fontWeight: '500',
    fontSize: 16,
  },
  buttonSecondary: {
    backgroundColor: '#f5f5f5',
    borderWidth: 1,
    borderColor: '#eee',
  },
  buttonSecondaryText: {
    color: '#333',
    fontWeight: '500',
    fontSize: 16,
  },
  detailsModalContent: {
  backgroundColor: '#fff',
  borderRadius: 12,
  padding: 16,
  margin: 24,
  maxHeight: '90%',
},
detailsHeader: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  marginBottom: 8,
},
detailsTitle: {
  fontSize: 20,
  fontWeight: 'bold',
  color: '#c1272d',
},
detailsTable: {
  borderRadius: 8,
  backgroundColor: '#fafafa',
  marginBottom: 12,
  padding: 8,
},
detailsRow: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  paddingVertical: 4,
  borderBottomWidth: 1,
  borderBottomColor: '#eee',
},
detailsLabel: {
  fontWeight: 'bold',
  width: '45%',
},
detailsValue: {
  width: '55%',
},
sectionHeader: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  marginVertical: 8,
},
sectionHeaderText: {
  fontWeight: 'bold',
  fontSize: 16,
},

contactsList: {
  maxHeight: 200,
},
contactRow: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  backgroundColor: '#f5f5f5',
  borderRadius: 6,
  padding: 8,
  marginVertical: 4,
},
contactInfo: { flex: 1 },
contactActions: { flexDirection: 'row' },
noteModalContent: { backgroundColor: '#fff',
  borderRadius: 12,
  padding: 16,
  margin: 24,
  maxHeight: '90%'},
contactModalContent: { backgroundColor: '#fff',
  borderRadius: 12,
  padding: 16,
  margin: 24,
  maxHeight: '90%'},
input: {
  borderWidth: 1,
  borderColor: '#ddd',
  borderRadius: 4,
  padding: 8,
  marginVertical: 6,
  backgroundColor: '#fafafa',
},
submitButton: {
  backgroundColor: '#c1272d',
  borderRadius: 5,
  paddingVertical: 10,
  paddingHorizontal: 24,
  alignItems: 'center',
  marginTop: 10,
},
submitButtonText: {
  color: '#fff',
  fontWeight: 'bold',
  fontSize: 16,
},
addNoteButton: {
  backgroundColor: '#c1272d',
  borderRadius: 5,
  paddingVertical: 8,
  paddingHorizontal: 12,
  marginTop: 10,
  alignSelf: 'flex-end',
},

});

export default styles;